name: amir
favicon: null
layout_spectrum: 0.44578
typography_spectrum: 0.58132
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff1020'
    - '#005290'
    - '#5282af'
    - '#fffffd'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
